### ISSUE TITLE
[FEAT]: Collab with Obsidian BRAT?

### ISSUE THREAD

**Issue by anonhostpi** [4Source/vare-obsidian-plugin#10]
### Description of the unfavorable solution

N/A

### Describe the feature you would like to have

N/A

### Additional context

It seems like these 2 plugins target similar functionality and are maintained at a similar frequency.

If that's the case, I'd like to suggest that you combine your efforts and move both into a gh org.

You are both MIT licensed, so it seems like you are both are on the same page about IP.

**Comment by anonhostpi** [comment]
relevant: https://github.com/TfTHacker/obsidian42-brat/issues/83

**Comment by 4Source** [comment]
Discussed at brat
